# Generated by Django 4.1.7 on 2023-03-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('ingredients', models.ManyToManyField(blank=True, related_name='ingredients', to='fridges.recipingredient')),
            ],
        ),
        migrations.CreateModel(
            name='FridgeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('pcs', 'штуки'), ('grams', 'граммы'), ('ml', 'миллилитры')], max_length=50)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fridges.fridge')),
                ('recip_ingredient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='fridges.recipingredient')),
            ],
        ),
    ]
